image:
  - Visual Studio 2017

clone_folder: c:\projects\source

environment:
  MSVC_DEFAULT_OPTIONS: ON
  BOOST_ROOT: C:\Libraries\boost_1_64_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_64_0\lib32-msvc-14.1

install:
    - mkdir C:\projects\deps
    - cd C:\projects\deps
    - set CMAKE_URL="https://cmake.org/files/v3.9/cmake-3.9.4-win64-x64.zip"
    - appveyor DownloadFile %CMAKE_URL% -FileName cmake.zip
    - 7z x cmake.zip -oC:\projects\deps > nul
    - move C:\projects\deps\cmake-* C:\projects\deps\cmake # Move to a version-agnostic directory
    - set PATH=C:\projects\deps\cmake\bin;%PATH%
    - cmake --version

build_script:
    - dir C:\projects
    - mkdir C:\projects\build
    - cd C:\projects\build
    - cmake c:\projects\source -G "Visual Studio 15"
    - cmake --build . --config "Debug"

test_script:
    - ctest -C Debug
